### ISSUE TITLE
Dynamic nested routes not working

### ISSUE THREAD

**Issue by seeARMS** [aiji42/next-qs-props#29]
Thanks for creating this! This is solving a real problem of mine. I'm running into one issue, though.

I run a blogging platform, and I have a unique structure of dynamic nested routes.

`/[...blogname].tsx`
`/[blogname]/[postname].tsx`

If users visit mysite.com/their-blog-page, the first route is successfully matched. If users visit mysite.com/their-blog-page/their-post, the second route matches. Users can also visit mysite.com/their-blog-page/settings/xyz, which matches the first route.

I'd like to use this middleware on the first route above, so I can (for example) use `page` query parameter to paginate my user's blog posts. This unfortunately does not work, since the plugin rewrites the Next route such that it matches the second route above!

I'm not sure how to fix this, but I'll keep trying.

**Comment by seeARMS** [comment]
I solved this by moving my second directory from:

`/[blogname]/[postname].tsx`

to

`/[blogname]/posts/[postname].tsx`

And creating another rewrite to append the `/posts`:

```
    const parts = pathname.split("/")

    if (parts.length != 3) {
      return NextResponse.next()
    }

    const rewrite = `/${parts[1]}/posts/${parts[2]}`
    return NextResponse.rewrite(rewrite)
```

Likely not a great solution, but it works.

**Comment by aiji42** [comment]
Hi @seeARMS,

Thanks for creating this valuable Issue.
Currently, there is no way to assign `/their-blog-page?page=x` to `/[...blogname].tsx` as long as there is `/[blogname]/[postname].tsx`.
I believe there are a lot of people who have the same problem as you, so I'd like to improve this library so that we can have more flexibility in how we convert paths for query strings.

If you could set up `/[blogname]/page/[number].tsx` and access to `/their-blog-page?page=2` could be assigned to `/their-blog-page/page/2`, it seems to me that your problem could be solved. If I modify this library in that way, will that help in your repository?

**Comment by aiji42** [comment]
I would like to close this issue as there has been no response for a long time.

**Comment by justswim** [comment]
hi @aiji42 I'm facing what I believe is the same issue.

I'd like to be able to create a site where I can paginate categories including the root category. For example:

/posts?page=2
/posts/announcements?page=3
/posts/opinion?page=4

is something like this currently possible with this library?
